build:
  buildCommand: |
    pip install -r backend/requirements.txt
  runtime: python3

services:
  - type: web
    name: ai-visibility-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/run.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
